plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.judohiroshi'
    compileSdk 34

    defaultConfig {
        applicationId "br.com.judohiroshi"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // Assina a versão "release" com a chave de debug para poder instalar direto no celular.
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
